### ISSUE TITLE
iOS client startup failed with "No parameterless constructor defined for type 'speech_to_text.MainPage'."

### ISSUE THREAD

**Issue by billylo1** [aptabase/aptabase-maui#11]
Any hints on how to resolve this?

```
Exception has occurred: System.MissingMethodException
No parameterless constructor defined for type 'speech_to_text.MainPage'.
    at at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
    at at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
    at at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
    at at System.Activator.CreateInstance(Type type, Boolean nonPublic)
    at at System.Activator.CreateInstance(Type type)
    at at Microsoft.Maui.Controls.ShellContent.<>c__DisplayClass19_0.<Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent>b__0()
    at at Microsoft.Maui.Controls.ElementTemplate.CreateContent()
    at at Microsoft.Maui.Controls.Internals.DataTemplateExtensions.CreateContent(DataTemplate self, Object item, BindableObject container)
    at at Microsoft.Maui.Controls.ShellContent.Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent()
    at at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.LoadRenderers()
    at at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.ViewDidLoad()
    at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:61
    at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:96
    at speech_to_text.Program.Main(String[] args) in /Users/billylo/Projects/c3po/speech-to-text/Platforms/iOS/Program.cs:13

```

**Comment by billylo1** [comment]
Never mind... forgot about this: 		`builder.Services.AddSingleton<MainPage>();`
